@echo off
if exist "Release" rd /s /q "Release" && echo Cleaning Release...
if exist "Debug"   rd /s /q "Debug"   && echo Cleaning Debug...
if exist "SLAP\Release" rd /s /q "SLAP\Release" && echo Cleaning SLAP\Release...
if exist "SLAP\Debug"   rd /s /q "SLAP\Debug"   && echo Cleaning SLAP\Debug...
if exist "Setup\Release" rd /s /q "Setup\Release" && echo Cleaning Setup\Release...
if exist "Setup\Debug"   rd /s /q "Setup\Debug"   && echo Cleaning Setup\Debug...
if exist "ipch"    rd /s /q "ipch"    && echo Cleaning ipch...
for /r %%i in (*.aps) do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.ncb) do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.sdf) do del /q "%%i" && echo Cleaning %%i...